# Default values for smarter-edge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  appName: home-orchestrator
  image: ghcr.io/smarter-project/home-orchestrator
  imageVersion: main

configuration:
  nameGuest: ollama
  portGuest: 31434
  nameHost: ollama
  portHost: 31435
  model: llama3.2:1b-instruct-q4_K_M
